### ISSUE TITLE
feat(android-foreground-service): support all Foreground service types

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-plugins#356]
### Plugin(s)

- [X] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Review
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Speech Recognition
- [ ] Speech Synthesis
- [ ] Torch
- [ ] Zip

### Current problem

The following error occurs on `startForegroundService` if not location permissions are granted:

```
Starting FGS with type location callerApp=ProcessRecord{6f07b46 32301:com.app/u0a347} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
                                                                                                   java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{6f07b46 32301:com.app/u0a347} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
                                                                                                   	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                                                   	at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                   	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                   	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                   	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
                                                                                                   	at android.app.Service.startForeground(Service.java:775)
                                                                                                   	at io.capawesome.capacitorjs.plugins.foregroundservice.AndroidForegroundService.onStartCommand(AndroidForegroundService.java:66)
                                                                                                   	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
                                                                                                   	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                   	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
                                                                                                   	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                   	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                   	at android.os.Looper.loop(Looper.java:319)
                                                                                                   	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                   	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                   Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                   	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2741)
                                                                                                   	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2452)
                                                                                                   	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1797)
                                                                                                   	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15948)
                                                                                                   	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11974)
```

### Preferred solution

The plugin should also support all [Foreground service types](https://developer.android.com/develop/background-work/services/fgs/service-types). There should be a new property `serviceType` in `StartForegroundServiceOptions`.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Closed by https://github.com/capawesome-team/capacitor-plugins/pull/358
