### ISSUE TITLE
bug: App closes unexpectly when device orientation changes

### ISSUE THREAD

**Issue by dtrigo** [capawesome-team/capacitor-plugins#76]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [X] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Error handling device orientation changes

FATAL EXCEPTION: CapacitorPlugins

                                                                                                    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                                                    	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10750)
                                                                                                    	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:9329)
                                                                                                    	at android.view.ViewRootImpl.die(ViewRootImpl.java:9314)
                                                                                                    	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:569)
                                                                                                    	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:510)
                                                                                                    	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:146)
                                                                                                    	at android.app.Dialog.dismissDialog(Dialog.java:676)
                                                                                                    	at android.app.Dialog.dismiss(Dialog.java:658)
                                                                                                    	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:192)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

### Expected behavior

Do not kill APP

### Reproduction

Just change device orientation while plugin open

### Steps to reproduce

1. In Android
2. Launch demo app
3. Open plugin
4. Change device orientation

### Other information

I solved by running the dialog inside a new Runnable on the Activity's ui thread

public void presentDatePicker(
        Date date,
        @Nullable Date minDate,
        @Nullable Date maxDate,
        @Nullable Locale locale,
        String cancelButtonText,
        String doneButtonText,
        @Nullable String theme,
        final PresentResultCallback resultCallback,
        @Nullable AndroidDatePickerMode androidDatePickerMode,
        @Nullable AndroidTimePickerMode androidTimePickerMode
    ) {
        if (locale != null) {
            this.updateLocaleConfiguration(locale);
        }

        Calendar calendar = this.createCalendarFromDate(date);

        plugin.getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {

                final DatePickerDialog dialog = new DatePickerDialog(
                    plugin.getContext(),
                    getTheme(theme, androidDatePickerMode, androidTimePickerMode),
                    (view, year, month, dayOfMonth) -> {
                        calendar.set(year, month, dayOfMonth);
                        resultCallback.success(calendar.getTime());
                    },
                    calendar.get(Calendar.YEAR),
                    calendar.get(Calendar.MONTH),
                    calendar.get(Calendar.DAY_OF_MONTH)
                );
        
                dialog.setOnDismissListener(_dialog -> resultCallback.dismiss());
                        dialog.create();
        
                Button doneButton = dialog.getButton(Dialog.BUTTON_POSITIVE);
                doneButton.setText(doneButtonText);
        
                Button cancelButton = dialog.getButton(Dialog.BUTTON_NEGATIVE);
                cancelButton.setText(cancelButtonText);
                cancelButton.setOnClickListener(
                    view -> {
                        resultCallback.cancel();
                        dialog.dismiss();
                    }
                );

                DatePicker picker = dialog.getDatePicker();
                if (minDate != null) {
                    picker.setMinDate(minDate.getTime());
                }
                if (maxDate != null) {
                    picker.setMaxDate(maxDate.getTime());
                }
        
                dialog.show();
            }
        });
    }

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/android: 5.4.0
  @capacitor/ios: 5.4.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/ios: 5.3.0

[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I cannot reproduce your issue.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.


https://github.com/capawesome-team/capacitor-plugins/assets/13857929/e2610e10-76ef-4df9-a853-dfd509f53334
